"""init schema

Revision ID: a9b081449f8a
Revises: c94f9c1d677e
Create Date: 2025-11-03 14:27:39.744686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9b081449f8a'
down_revision: Union[str, Sequence[str], None] = 'c94f9c1d677e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atributo', sa.Column('es_primaria', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('atributo', 'es_primaria')
    # ### end Alembic commands ###
